-- AlterTable
ALTER TABLE "User" ADD COLUMN     "tokenLimitPerMonth" INTEGER NOT NULL DEFAULT 50000,
ADD COLUMN     "tokenResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "tokensUsedThisMonth" INTEGER NOT NULL DEFAULT 0;
