export enum NotificationChannelTypeEnum {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
}

export enum NotificationStatusEnum {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum NotificationTypeEnum {
  USER_ONBOARDING_WELCOME = 'USER_ONBOARDING_WELCOME',
  USER_ONBOARDING_EMAIL_VERIFICATION = 'USER_ONBOARDING_EMAIL_VERIFICATION',
  PASSWORD_RESET_OTP = 'PASSWORD_RESET_OTP',
  AFFIRMATION_GENERATED = 'AFFIRMATION_GENERATED',
  STREAK_MILESTONE = 'STREAK_MILESTONE',
  STREAK_REMINDER = 'STREAK_REMINDER',
  SESSION_COMPLETED = 'SESSION_COMPLETED',
}

